# Generated by Django 5.2.11 on 2026-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw'), ('*', 'Undecided')], default='*', max_length=10)),
                ('elo_change_p1', models.IntegerField(default=0, help_text='ELO delta applied to player 1.')),
                ('elo_change_p2', models.IntegerField(default=0, help_text='ELO delta applied to player 2.')),
                ('time_control', models.CharField(default='5+3', help_text="Time control string, e.g. '3+1', '5+3', '10+0'.", max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
