# Generated by Django 5.2.1 on 2026-02-18 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('tournaments', '0003_update_game_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='elo_change_p1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='elo_change_p2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.AddField(
            model_name='game',
            name='armageddon_of',
            field=models.OneToOneField(blank=True, help_text='If set, this game is the Armageddon tiebreak for the linked game.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armageddon_game', to='games.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='black_time',
            field=models.FloatField(default=180.0, help_text="Black's remaining clock in seconds."),
        ),
        migrations.AddField(
            model_name='game',
            name='current_fen',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_change_black',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='elo_change_white',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='increment',
            field=models.IntegerField(default=1, help_text='Increment per move in seconds.'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_tournament_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='last_move_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='move_list',
            field=models.JSONField(default=list, help_text="Ordered list of UCI move strings, e.g. ['e2e4','e7e5',…]."),
        ),
        migrations.AddField(
            model_name='game',
            name='pgn',
            field=models.TextField(blank=True, help_text='Full PGN text, built incrementally.'),
        ),
        migrations.AddField(
            model_name='game',
            name='result_reason',
            field=models.CharField(blank=True, help_text="e.g. 'checkmate', 'timeout', 'stalemate', 'resignation'.", max_length=60),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for opponent'), ('ongoing', 'Ongoing'), ('white_wins', 'White wins'), ('black_wins', 'Black wins'), ('draw', 'Draw'), ('timeout_white', 'White timed out'), ('timeout_black', 'Black timed out'), ('aborted', 'Aborted')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_match',
            field=models.ForeignKey(blank=True, help_text='The tournament Match this game belongs to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='tournaments.match'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time',
            field=models.FloatField(default=180.0, help_text="White's remaining clock in seconds."),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.CharField(default='3+1', help_text="Format: '<base_minutes>+<increment_seconds>'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
