# Generated by Django 5.2.1 on 2026-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_add_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('chess', 'Chess'), ('breakthrough', 'Breakthrough')], default='chess', max_length=20),
        ),
    ]
