# Generated by Django 5.2.11 on 2026-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_thinking_seconds',
            field=models.FloatField(default=1.0, help_text='Maximum seconds allowed for AI to think per move.'),
        ),
    ]
