# Generated by Django 5.2.11 on 2026-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_ai_thinking_seconds_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_thinking_seconds',
            field=models.FloatField(db_default=1.0, default=0.0, help_text='Maximum seconds allowed for AI to think per move.'),
        ),
    ]
