# Generated by Django 5.2.11 on 2026-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_ai_thinking_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_thinking_seconds',
            field=models.FloatField(default=1.0, help_text="Max seconds Black's AI gets to think per move."),
        ),
        migrations.AddField(
            model_name='game',
            name='white_thinking_seconds',
            field=models.FloatField(default=1.0, help_text="Max seconds White's AI gets to think per move."),
        ),
    ]
