# Generated by Django 5.2.11 on 2026-08-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_thinking_seconds',
            field=models.FloatField(db_default=1.0, default=0.0, help_text='Deprecated — use white_thinking_seconds / black_thinking_seconds. Kept for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='black_thinking_seconds',
            field=models.FloatField(default=5.0, help_text="Target pace, in seconds, for Black's AI moves. Actual move time may exceed this depending on how the opponent's model is hosted."),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_thinking_seconds',
            field=models.FloatField(default=5.0, help_text="Target pace, in seconds, for White's AI moves. Actual move time may exceed this depending on how the opponent's model is hosted."),
        ),
    ]
