# Generated by Django 5.2.11 on 2026-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.PositiveIntegerField()),
                ('bracket_position', models.PositiveIntegerField(default=0, help_text='Position within the round (0‑indexed) for bracket rendering.')),
                ('result', models.CharField(blank=True, help_text="'1-0', '0-1', or '1/2-1/2'.", max_length=10)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('is_armageddon', models.BooleanField(default=False, help_text='True if this is an Armageddon tiebreak game.')),
                ('time_control', models.CharField(default='3+1', help_text="'3+1' for normal, '2+1' for Armageddon white, '1+0' for Armageddon black.", max_length=20)),
                ('elo_change_p1', models.IntegerField(default=0)),
                ('elo_change_p2', models.IntegerField(default=0)),
                ('duration', models.DurationField(blank=True, help_text='How long the match lasted.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tournament', 'round_num', 'bracket_position', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('small', 'Small (128 players)'), ('large', 'Large (1024 players)')], default='small', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('beginner', 'Beginner (≤1200)'), ('intermediate', 'Intermediate (1201‑1600)'), ('advanced', 'Advanced (1601‑2000)'), ('expert', 'Expert (2001+)')], help_text='Fixed for small tournaments; large tournaments rotate categories each round.', max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(default=128, help_text='128 for small, 1024 for large.')),
                ('rounds_total', models.PositiveIntegerField(default=7, help_text='7 for small, 10 for large.')),
                ('current_round', models.PositiveIntegerField(default=0, help_text='Currently active round (0 = not started).')),
                ('status', models.CharField(choices=[('open', 'Open for registration'), ('full', 'Full'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='open', max_length=20)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, help_text='Prize pool in platform currency. Rolls over if not fully awarded.', max_digits=12)),
                ('rollover_amount', models.DecimalField(decimal_places=2, default=0, help_text='Unclaimed prize that rolls into the next tournament.', max_digits=12)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
