# Generated by Django 5.2.1 on 2026-02-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_update_game_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('small', 'Small (128 players)'), ('large', 'Large (1024 players)'), ('qa', 'QA (2 players)')], default='small', max_length=10),
        ),
    ]
