# Generated by Django 5.2.1 on 2026-02-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_time_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='announcement',
            field=models.TextField(blank=True, help_text='Auto-generated announcement text after completion.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('elimination', 'Single Elimination'), ('swiss', 'Swiss System')], default='elimination', help_text='Bracket format for this tournament.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, help_text='Gauntlet week number (auto-incremented).', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Open for registration'), ('full', 'Full'), ('upcoming', 'Upcoming (auto-scheduled)'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('small', 'Small (128 players)'), ('large', 'Large (1024 players)'), ('qa', 'QA (2 players)'), ('gauntlet', 'Gladiator Gauntlet (Swiss)')], default='small', max_length=10),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('gauntlet_champion', 'Gauntlet Champion'), ('gauntlet_top3', 'Gauntlet Top 3'), ('win_streak_5', '5-Win Streak'), ('win_streak_10', '10-Win Streak')], max_length=30)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'Gauntlet Champion Week 12'.", max_length=120)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='GauntletStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='1 per win, 0.5 per draw, 0 per loss.')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Final rank (set after each round).')),
                ('buchholz', models.FloatField(default=0.0, help_text="Sum of opponents' scores — first tiebreaker in Swiss.")),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauntlet_standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-buchholz', '-wins'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
