# Generated by Django 5.2.11 on 2026-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_add_tournament_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('chess', 'Chess'), ('breakthrough', 'Breakthrough')], default='chess', help_text='Game type for this tournament.', max_length=20),
        ),
    ]
