# Generated by Django 5.2.11 on 2026-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_probabilistic_sha_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tournamentshacheck',
            new_name='tournaments_tournam_0dad58_idx',
            old_name='tournaments_t_tournam_e8c1bd_idx',
        ),
        migrations.RenameIndex(
            model_name='tournamentshacheck',
            new_name='tournaments_result_fe9553_idx',
            old_name='tournaments_t_result_3ad29f_idx',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.PositiveIntegerField(default=16, help_text='16 for Gladiator Gauntlet, 2 for QA.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner (≤1200)'), ('intermediate', 'Intermediate (1201‑1600)'), ('advanced', 'Advanced (1601‑2000)'), ('expert', 'Expert (2001+)')], help_text='Category for this tournament (mainly relevant for Gauntlet).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds_total',
            field=models.PositiveIntegerField(default=5, help_text='5 for Gladiator Gauntlet, 1 for QA.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('qa', 'QA (2 players)'), ('gauntlet', 'Gladiator Gauntlet (Swiss)')], default='gauntlet', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='last_sha_check_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last probabilistic SHA audit performed on this participant. Used by run_probabilistic_sha_audit to score 'time-since-last-check' as a check probability factor.", null=True),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='sha_anomaly_history',
            field=models.BooleanField(default=False, help_text='True if this participant has ever triggered a SHA mismatch that was manually cleared/forgiven by an admin. Increases their probability of being audited again.'),
        ),
        migrations.AlterField(
            model_name='tournamentshacheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
