# Generated by Django 5.2.1 on 2026-06-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_rename_tournaments_t_tournam_e8c1bd_idx_tournaments_tournam_0dad58_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_money_tournament',
            field=models.BooleanField(default=False, help_text='Whether this tournament has a cash prize. Restricts entry to eligible regions.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payout_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payout status — only relevant for money tournaments.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prize amount in prize_currency. Leave blank for non-money tournaments.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_currency',
            field=models.CharField(blank=True, default='ILS', help_text='ISO 4217 currency code for the prize (e.g. ILS, USD).', max_length=3),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_text',
            field=models.TextField(blank=True, help_text='Legal terms text participants must accept before joining a money tournament.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terms_version',
            field=models.CharField(blank=True, help_text="Version string for terms (e.g. '1.0'). Increment to require re-acceptance.", max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='geo_eligible',
            field=models.BooleanField(blank=True, help_text='True = eligible country, False = ineligible, None = geo check not run.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='join_country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code resolved from join_ip.', max_length=2),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='join_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP address recorded at registration time (money tournaments only).', null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the participant accepted the tournament terms.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='terms_version_accepted',
            field=models.CharField(blank=True, help_text='Version of tournament terms the participant accepted.', max_length=20),
        ),
    ]
