# Generated by Django 5.2.11 on 2026-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_tournament_prize_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='ai_thinking_seconds',
            field=models.FloatField(choices=[(0.5, '0.5s'), (1.0, '1s'), (2.0, '2s'), (5.0, '5s'), (10.0, '10s')], default=1.0, help_text="Max seconds this participant's AI gets to think per move, chosen at registration."),
        ),
    ]
