# Generated by Django 5.2.11 on 2026-08-23 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournamentparticipant_ai_thinking_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('paypal_email', models.EmailField(help_text="Snapshotted from TournamentParticipant.paypal_email at claim-creation time — do NOT live-reference the participant row, so later profile edits can't silently change payout destination.", max_length=254)),
                ('claim_code', models.CharField(db_index=True, max_length=48, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='created_at + 30 days')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('paid_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_claim', to='tournaments.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prize Claim',
                'verbose_name_plural': 'Prize Claims',
            },
        ),
    ]
