# Generated by Django 5.2.11 on 2026-08-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_prizeclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='ai_thinking_seconds',
            field=models.FloatField(choices=[(3.0, '3s'), (5.0, '5s'), (8.0, '8s'), (12.0, '12s'), (15.0, '15s')], default=5.0, help_text="Max seconds this participant's AI gets to think per move, chosen at registration."),
        ),
    ]
