# Generated by Django 5.2.11 on 2026-08-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_eligibility_payout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eligibilityverification',
            new_name='tournaments_status_3bbd6e_idx',
            old_name='tournaments_eligib_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutconfirmation',
            new_name='tournaments_confirm_51de88_idx',
            old_name='tournaments_payout_confirmed_idx',
        ),
    ]
