# Generated by Django 5.2.11 on 2026-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_participant_data_space_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('qa', 'QA (2 players)'), ('gauntlet', 'Gladiator Gauntlet')], default='gauntlet', max_length=10),
        ),
    ]
