# Generated by Django 5.2.1 on 2026-09-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_alter_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='registered_space_sha',
        ),
    ]
