# Generated by Django 5.2.17 on 2026-10-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_remove_tournamentparticipant_registered_space_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('qa', 'QA (2 players)'), ('gauntlet', 'Gladiator Gauntlet'), ('gladiatormania', 'The Gladiatormania')], default='gauntlet', max_length=20),
        ),
    ]
