# Generated by Django 5.2.17 on 2026-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_gladiatormania_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='accepted_terms_slug',
            field=models.SlugField(blank=True, default='', help_text='Slug of the TournamentTerms record the participant accepted.', max_length=80),
        ),
        migrations.CreateModel(
            name='TournamentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(help_text='e.g. 1.0', max_length=20)),
                ('body', models.TextField(help_text='HTML. May use {{ tournament.prize_amount }}, {{ tournament.prize_currency }}, {{ tournament.name }} and {{ terms.title }}.')),
                ('requires_age_18', models.BooleanField(default=False)),
                ('requires_israeli_residency', models.BooleanField(default=False)),
                ('has_prize', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tournament terms',
                'verbose_name_plural': 'tournament terms',
                'ordering': ['slug', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='uniq_tournamentterms_slug_version')],
            },
        ),
    ]
