# Generated by Django 5.2.17 on 2026-10-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_tournamentterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='terms',
            field=models.ForeignKey(blank=True, help_text='Terms & Conditions record shown on the join page. Leave empty to use the legacy Gauntlet terms. Only for Gauntlet / Gladiatormania.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.tournamentterms'),
        ),
    ]
