# Generated by Django 5.2.17 on 2026-10-01 21:09

import apps.tournaments.countries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_seed_tournament_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allowed_countries',
            field=models.JSONField(default=apps.tournaments.countries.default_allowed_countries, help_text='ISO 3166-1 alpha-2 country codes whose residents may enter, e.g. IL or IN. Israel only by default; only The Gladiatormania can use other countries.'),
        ),
    ]
