# Generated by Django 5.2.17 on 2026-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_tournament_allowed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='declared_residency_countries',
            field=models.CharField(blank=True, default='', help_text='Countries named in the residency declaration the participant ticked at joining, comma-separated ISO codes. Compare with join_country_code (derived from the IP).', max_length=100),
        ),
    ]
