# Generated by Django 5.2.17 on 2026-10-01 21:56

import apps.tournaments.sensitive
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_participant_declared_residency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='claim_deadline_days',
            field=models.PositiveIntegerField(default=30, help_text='Days the winner has to complete the prize claim, counted while the next step is theirs.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payout_instructions',
            field=models.TextField(blank=True, help_text='Shown on the terms page. Never put bank or UPI details here.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='payout_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('other', 'Other')], default='paypal', help_text='How the prize is paid. PayPal asks the winner for a PayPal email; the other methods are arranged by AGL by email. Bank or UPI details are never stored.', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_hold_reason',
            field=models.TextField(blank=True, help_text='Internal note. Never shown to players.', validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_on_hold',
            field=models.BooleanField(default=False, help_text='Stops new prize claims and payouts. Nothing is deleted. To release: untick, then run backfill_prize_claim if no claim was created.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='verification_documents',
            field=models.TextField(blank=True, help_text='Documents the winner may be asked to show, one per line. Terms can print them with {{ tournament.verification_documents_list }}. Aadhaar must not be requested.'),
        ),
    ]
