# Generated by Django 5.2.17 on 2026-10-01 22:18

import apps.tournaments.sensitive
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_tournament_payout_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconfirmation',
            name='contact_email_snapshot',
            field=models.EmailField(blank=True, help_text='Account email AGL will use for non-PayPal payouts.', max_length=254),
        ),
        migrations.AddField(
            model_name='payoutconfirmation',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutconfirmation',
            name='contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutconfirmation',
            name='payout_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payoutconfirmation',
            name='terms_slug',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payoutconfirmation',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='blocked_reason',
            field=models.TextField(blank=True, validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='expiry_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Free text, e.g. a transfer reference. Never an account or UPI number.', max_length=100, validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='payout_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('other', 'Other')], default='paypal', help_text="Snapshot of the tournament's payout method when the claim was created.", max_length=20),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='status_before_block',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='prizeclaim',
            name='tax_withheld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityverification',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Record who checked and when, never document numbers (passport, PAN, bank, UPI). Required when rejecting.', validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AlterField(
            model_name='eligibilityverification',
            name='verification_method',
            field=models.CharField(blank=True, help_text="How the check was performed, e.g. 'video call' or 'live ID review, not retained'. No file upload. Never enter document numbers.", max_length=200, validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AlterField(
            model_name='payoutconfirmation',
            name='paypal_email_snapshot',
            field=models.EmailField(blank=True, help_text="Copy of the user's PayPal email at the moment they confirmed (PayPal payouts only).", max_length=254),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Never enter bank, UPI, PAN or document numbers.', validators=[apps.tournaments.sensitive.validate_no_sensitive_data]),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text="Snapshotted from TournamentParticipant.paypal_email at claim-creation time — do NOT live-reference the participant row, so later profile edits can't silently change payout destination. Empty for non-PayPal payouts.", max_length=254),
        ),
        migrations.AlterField(
            model_name='prizeclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('paid', 'Paid'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PrizeClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked'), ('contacted', 'Payment details requested'), ('payment_recorded', 'Payment details recorded'), ('note', 'Note'), ('expiry_paused', 'Expiry clock paused'), ('expiry_resumed', 'Expiry clock resumed')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, validators=[apps.tournaments.sensitive.validate_no_sensitive_data])),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.prizeclaim')),
            ],
            options={
                'verbose_name': 'Prize Claim Event',
                'verbose_name_plural': 'Prize Claim Events',
                'ordering': ['at', 'pk'],
            },
        ),
    ]
