# Generated by Django 5.2.1 on 2026-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0036_seed_india_terms_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='profile_country_code',
            field=models.CharField(blank=True, default='', help_text="Country on the user's profile at the moment of joining (ISO 3166-1 alpha-2). A staff-visible signal to compare with join_country_code (IP) and declared_residency_countries; a disagreement never blocks anything.", max_length=2),
        ),
    ]
