# Generated by Django 5.2.1 on 2026-10-05 18:01

import apps.tournaments.countries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0037_country_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='allowed_countries',
            field=models.JSONField(blank=True, default=apps.tournaments.countries.default_allowed_countries, help_text='ISO 3166-1 alpha-2 country codes whose residents may enter, e.g. IL or IN. Leave empty to open the tournament to all countries.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='terms',
            field=models.ForeignKey(blank=True, help_text='Terms & Conditions record shown on the join page. Leave empty to use the legacy Gauntlet terms.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.tournamentterms'),
        ),
    ]
