# Generated by Django 5.2.1 on 2026-09-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short preview shown in the feed. Auto-generated from the body if left blank.')),
                ('body', models.TextField(help_text='Markdown supported: **bold**, *italic*, `code`, [links](url).')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. "tournaments, changelog".', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time this post is published.', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
                'indexes': [models.Index(fields=['status', 'is_pinned', '-published_at'], name='news_newspo_status_4c8572_idx')],
            },
        ),
    ]
