#!/usr/bin/env python3
"""Sandbox inference — runs inside Docker container.
Auto-generated by Agladiator. Do not edit."""
import json
import os
import sys

GAME_TYPE = os.environ.get("GAME_TYPE", "chess")
FEN = os.environ.get("FEN", "")
PLAYER = os.environ.get("PLAYER", "w")
DATA_DIR = os.environ.get("DATA_DIR", "")


def _load_zone_db_from_data():
    """Try to load the zone database from the DATA_DIR mount (/data)."""
    if not DATA_DIR or not os.path.isdir(DATA_DIR):
        return None
    # Read zone_db_filename from config
    zone_filename = "zone_db.npz"
    config_path = "/model/config_model.json"
    if os.path.exists(config_path):
        try:
            with open(config_path) as f:
                cfg = json.load(f)
            zone_filename = cfg.get("zone_db_filename", zone_filename)
        except Exception:
            pass
    zone_path = os.path.join(DATA_DIR, zone_filename)
    if os.path.exists(zone_path):
        try:
            import numpy as np
            return np.load(zone_path, allow_pickle=True)
        except Exception:
            pass
    return None


def try_official_handler():
    """Use the platform's official handler modules mounted at /agl_handlers.

    The sandbox mounts the platform handlers into /agl_handlers. We prefer
    the official handlers over any user-provided handler.py in the model
    repository. These handlers are authored by the platform and import
    the cached model files from /model.
    """
    # Ensure our mounted handlers directory is on sys.path
    try:
        if os.path.isdir("/agl_handlers") and "/agl_handlers" not in sys.path:
            sys.path.insert(0, "/agl_handlers")
    except Exception:
        pass

    try:
        if GAME_TYPE == "breakthrough":
            # Official Breakthrough handler
            import official_breakthrough_handler as oh
            print("✅ Using OFFICIAL Breakthrough handler (ignoring user's handler.py)")
        else:
            # Official Chess handler
            import official_chess_handler as oh
            print("✅ Using OFFICIAL Chess handler (ignoring user's handler.py)")

        # Instantiate the handler with the mounted model path
        handler = oh.EndpointHandler(path="/model")
        print(f"✅ Loading model weights from cache: /model")

        # If the handler needs a zone_db and it wasn't loaded, provide it
        if getattr(handler, "zone_db", None) is None and DATA_DIR:
            zone_db = _load_zone_db_from_data()
            if zone_db is not None:
                handler.zone_db = zone_db
                if hasattr(handler, "_init_predictor"):
                    handler._init_predictor()

        return handler({"inputs": {"fen": FEN, "player": PLAYER, "game_type": GAME_TYPE}})
    except Exception:
        return None


def try_transformers_chess():
    """Standard Transformers loading for chess models."""
    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer
        import torch

        model = AutoModelForCausalLM.from_pretrained(
            "/model", use_safetensors=True, trust_remote_code=False,
        )
        # Load tokenizer: prefer fast tokenizer but fallback to slow if fast
        # conversion requires optional dependencies (sentencepiece/tiktoken).
        try:
            tokenizer = AutoTokenizer.from_pretrained(
                "/model", trust_remote_code=False,
            )
        except Exception as e:
            # Retry with slow tokenizer
            try:
                tokenizer = AutoTokenizer.from_pretrained(
                    "/model", trust_remote_code=False, use_fast=False,
                )
            except Exception:
                raise
        model.eval()

        inputs = tokenizer(FEN, return_tensors="pt")
        with torch.no_grad():
            outputs = model.generate(
                **inputs, max_new_tokens=10,
                do_sample=False, temperature=1.0,
            )
        decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
        # Extract UCI move from output
        for part in reversed(decoded.strip().split()):
            p = part.strip()
            if len(p) >= 4 and p[0] in "abcdefgh" and p[1] in "12345678":
                return p[:5] if len(p) == 5 and p[4] in "qrbnQRBN" else p[:4]
        return decoded.strip()
    except Exception:
        return None


def main():
    result = try_custom_handler()
    if result is None and GAME_TYPE == "chess":
        result = try_transformers_chess()
    if result is None:
        print("ERROR:no_result", file=sys.stderr)
        sys.exit(1)

    move = None
    if isinstance(result, str):
        move = result.strip()
    elif isinstance(result, dict):
        move = result.get("move") or result.get("output", "")
    elif isinstance(result, list) and result:
        item = result[0]
        if isinstance(item, dict):
            move = item.get("move") or item.get("output", "")
        elif isinstance(item, str):
            move = item.strip()
    elif isinstance(result, bytes):
        move = result.decode("utf-8", errors="replace").strip()

    if move:
        print(f"MOVE:{move}", flush=True)
    else:
        print("ERROR:empty_result", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
