# Generated by Django 5.2.1 on 2026-03-04 16:21

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ai_file',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hf_model_repo_id',
            field=models.CharField(blank=True, help_text='Hugging Face repo ID for your chess model (e.g. austindavis/ChessGPT_d12).', max_length=255, validators=[apps.users.models.validate_hf_repo_id]),
        ),
    ]
