# Generated by Django 5.2.1 on 2026-03-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_replace_ai_file_with_hf_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ai_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
