# Generated by Django 5.2.1 on 2026-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_dob_country_ai_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hf_token',
            field=models.CharField(blank=True, help_text='Hugging Face read token for gated model access.', max_length=512),
        ),
    ]
