# Generated by Django 5.2.11 on 2026-03-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_hf_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hf_token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
