# Generated by Django 5.2.11 on 2026-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_hf_token_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_known_commit_id',
            field=models.CharField(blank=True, help_text="Most recent commit SHA seen for this user's HF model repo.", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the model was locked after 30 rated games.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_commit_id',
            field=models.CharField(blank=True, help_text='Commit SHA of the HF model at the time the user reached 30 rated games.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rated_games_played',
            field=models.PositiveIntegerField(default=0, help_text='Number of rated games completed with the current AI agent.'),
        ),
    ]
