# Generated by Django 5.2.1 on 2026-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_rating_lock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_model_validation_date',
            field=models.DateField(blank=True, help_text='Date (UTC) of the most recent successful daily model integrity check.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='model_integrity_ok',
            field=models.BooleanField(default=True, help_text='False = model changed or needs re-validation. Blocks rated/tournament play.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='original_model_commit_sha',
            field=models.CharField(blank=True, help_text='Commit SHA recorded at registration — the baseline for integrity checks.', max_length=40, null=True),
        ),
    ]
