# Generated by Django 5.2.1 on 2026-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_model_integrity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_full_sha',
            field=models.CharField(blank=True, help_text='Exact immutable commit SHA approved at submission.', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pinned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this model version was approved/pinned.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_repo_id',
            field=models.CharField(blank=True, help_text="HF repo ID at submission time (e.g. 'user/my-model').", max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submission_repo_type',
            field=models.CharField(blank=True, default='model', help_text="HF repo type at submission time (e.g. 'model').", max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submitted_by_user',
            field=models.CharField(blank=True, help_text='HF username of the person who submitted this model.', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='submitted_ref',
            field=models.CharField(blank=True, help_text="Branch or tag the user chose at submission (e.g. 'main', 'v1.0').", max_length=255),
        ),
    ]
