# Generated by Django 5.2.1 on 2026-03-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_approved_full_sha_customuser_pinned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hf_oauth_linked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user linked their HF account via OAuth.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hf_oauth_token_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted HF OAuth access token for API calls.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hf_username',
            field=models.CharField(blank=True, help_text='Hugging Face username obtained via OAuth.', max_length=255),
        ),
    ]
