# Generated by Django 5.2.1 on 2026-04-02 21:25

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_hf_oauth_linked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hf_model_repo_id',
            field=models.CharField(blank=True, help_text='DEPRECATED — use UserGameModel. Legacy chess repo ID.', max_length=255, validators=[apps.users.models.validate_hf_repo_id]),
        ),
        migrations.CreateModel(
            name='UserGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('chess', 'Chess'), ('breakthrough', 'Breakthrough')], max_length=20)),
                ('hf_model_repo_id', models.CharField(help_text='Hugging Face repo ID for this game (e.g. austindavis/ChessGPT_d12).', max_length=255, validators=[apps.users.models.validate_hf_repo_id])),
                ('original_model_commit_sha', models.CharField(blank=True, help_text='Commit SHA recorded at submission — baseline for integrity checks.', max_length=40, null=True)),
                ('last_known_commit_id', models.CharField(blank=True, help_text='Most recent commit SHA seen for this model.', max_length=40, null=True)),
                ('model_integrity_ok', models.BooleanField(default=True, help_text='False = model changed or needs re-validation.')),
                ('last_model_validation_date', models.DateField(blank=True, help_text='Date (UTC) of the most recent successful integrity check.', null=True)),
                ('locked_commit_id', models.CharField(blank=True, help_text='Commit SHA frozen after the rated-game threshold.', max_length=40, null=True)),
                ('rated_games_played', models.PositiveIntegerField(default=0, help_text='Number of rated games completed with this model.')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when the model was locked after reaching the game threshold.', null=True)),
                ('submission_repo_type', models.CharField(blank=True, default='model', max_length=20)),
                ('submitted_ref', models.CharField(blank=True, help_text="Branch or tag chosen at submission (e.g. 'main').", max_length=255)),
                ('approved_full_sha', models.CharField(blank=True, help_text='Exact immutable commit SHA approved at submission.', max_length=40)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game Model',
                'verbose_name_plural': 'User Game Models',
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
