# Generated by Django 5.2.1 on 2026-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_usergamemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='rated_games_since_revalidation',
            field=models.PositiveIntegerField(default=0, help_text='Rated games played since the last integrity re-validation. Must reach 30 before tournament entry after a revision change.'),
        ),
    ]
