# Generated by Django 5.2.1 on 2026-04-04 21:17

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usergamemodel_rated_games_since_revalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='hf_data_repo_id',
            field=models.CharField(blank=True, help_text='Hugging Face data repo ID (e.g. username/breakthrough-data). Used for Breakthrough only.', max_length=255, validators=[apps.users.models.validate_hf_repo_id]),
        ),
    ]
