# Generated by Django 5.2.11 on 2026-04-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_sandbox_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_name',
            field=models.CharField(blank=True, help_text='DEPRECATED. Kept for backwards compatibility.', max_length=120),
        ),
        migrations.AlterField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_url',
            field=models.URLField(blank=True, help_text='DEPRECATED. Kept for backwards compatibility.', max_length=500),
        ),
    ]
