# Generated by Django 5.2.11 on 2026-04-06 20:41

from django.db import migrations, models


def deduplicate_ai_names(apps, schema_editor):
    """Append '_N' suffix to duplicate ai_name values before adding unique constraint."""
    CustomUser = apps.get_model("users", "CustomUser")
    # Convert empty strings to NULL so they don't conflict
    CustomUser.objects.filter(ai_name="").update(ai_name=None)
    # Find duplicated ai_names (case-insensitive)
    from django.db.models import Count
    dupes = (
        CustomUser.objects.filter(ai_name__isnull=False)
        .values("ai_name")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for entry in dupes:
        users = list(
            CustomUser.objects.filter(ai_name=entry["ai_name"]).order_by("date_joined")
        )
        # Keep the first user's name unchanged, rename the rest
        for i, user in enumerate(users[1:], start=2):
            user.ai_name = f"{user.ai_name}_{i}"
            user.save(update_fields=["ai_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usergamemodel_hf_inference_endpoint_name_and_more'),
    ]

    operations = [
        # Step 1: allow NULL (needed before dedup so blanks become NULL)
        migrations.AlterField(
            model_name='customuser',
            name='ai_name',
            field=models.CharField(blank=True, help_text="Display name for this user's AI bot.", max_length=120, null=True),
        ),
        # Step 2: deduplicate existing rows
        migrations.RunPython(deduplicate_ai_names, migrations.RunPython.noop),
        # Step 3: add unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='ai_name',
            field=models.CharField(blank=True, help_text="Display name for this user's AI bot.", max_length=120, null=True, unique=True),
        ),
    ]
