# Generated by Django 5.2.11 on 2026-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_unique_ai_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='cached_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the cached model files were written.', null=True),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='cached_commit',
            field=models.CharField(blank=True, help_text='Commit SHA corresponding to the cached snapshot.', max_length=40),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='cached_path',
            field=models.CharField(blank=True, help_text="Filesystem path to the user's cached model directory.", max_length=1024),
        ),
    ]
