# Generated by Django 5.2.11 on 2026-04-21 15:09

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_usergamemodel_cached_at_usergamemodel_cached_commit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_id',
            field=models.CharField(blank=True, default='', help_text='HF Inference Endpoint ID (for compatibility with DB, can be blank)', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usergamemodel',
            name='hf_data_repo_id',
            field=models.CharField(blank=True, help_text='Hugging Face data repo ID (e.g. username/breakthrough-data or username/chess-data). Used for Breakthrough and Chess.', max_length=255, validators=[apps.users.models.validate_hf_repo_id]),
        ),
    ]
