# Generated by Django 5.2.11 on 2026-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_usergamemodel_hf_inference_endpoint_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_status',
            field=models.CharField(blank=True, default='', help_text='HF Inference Endpoint status (compatibility field, can be blank)', max_length=40, null=True),
        ),
    ]
