# Generated by Django 5.2.11 on 2026-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_usergamemodel_hf_inference_endpoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='sandbox_verified',
            field=models.BooleanField(default=False, help_text='True when sandbox verification passed and model cached for live play.'),
        ),
    ]
