# Generated by Django 5.2.11 on 2026-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_allow_null_endpoint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True once the user has proven repo ownership via AGL_VERIFY.txt challenge.'),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='repo_last_modified_at_registration',
            field=models.DateTimeField(blank=True, help_text='Latest commit timestamp of the repo at tournament registration. Used to detect post-registration changes.', null=True),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Challenge code the user must place in AGL_VERIFY.txt to prove ownership.', max_length=64),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='verification_code_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the verification challenge code was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful ownership verification.', null=True),
        ),
    ]
