# Generated by Django 5.2.11 on 2026-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_ownership_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elo_breakthrough',
            field=models.IntegerField(db_default=1200, default=1200, help_text='ELO rating for Breakthrough games only.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='elo_chess',
            field=models.IntegerField(db_default=1200, default=1200, help_text='ELO rating for Chess games only.'),
        ),
    ]
