# Generated by Django 5.2.11 on 2026-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_add_per_game_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='data_repo_ownership_verified',
            field=models.BooleanField(default=False, help_text='True when AGL_VERIFY.txt in the data repo matches the verification code.'),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='model_repo_ownership_verified',
            field=models.BooleanField(default=False, help_text='True when AGL_VERIFY.txt in the model repo matches the verification code.'),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='space_ownership_verified',
            field=models.BooleanField(default=False, help_text='True when AGL_VERIFY.txt in the HF Space repo matches the verification code.'),
        ),
    ]
