# Generated by Django 5.2.1 on 2026-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_add_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='current_repo_sha',
            field=models.CharField(blank=True, help_text='SHA of the repo at the time it was last verified/approved.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='new_repo_sha',
            field=models.CharField(blank=True, help_text='SHA of the incoming repo when a change is detected.', max_length=64, null=True),
        ),
    ]
