# Generated by Django 5.2.1 on 2026-09-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_add_space_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='space_last_latency_ms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='space_last_verified_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='space_status',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='approved_space_sha',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='current_space_sha',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_id',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_name',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_status',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='hf_inference_endpoint_url',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='new_space_sha',
        ),
        migrations.RemoveField(
            model_name='usergamemodel',
            name='space_ownership_verified',
        ),
    ]
