# Generated by Django 5.2.1 on 2026-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_customuser_space_last_latency_ms_and_more'),
    ]

    operations = [
        # The `is_official_bot` column already exists in SOME databases (added
        # by an older, now-missing "0034_add_official_bot_flags" migration
        # whose file was lost, though its django_migrations row remains) —
        # but NOT on a fresh database (e.g. Django's test DB, rebuilt from
        # migrations on every `manage.py test` run). Django never re-runs a
        # migration once it's recorded as applied in django_migrations, so
        # running the real AddField here is safe for already-migrated
        # databases and required for fresh ones.
        migrations.AddField(
            model_name='customuser',
            name='is_official_bot',
            field=models.BooleanField(default=False),
        ),
    ]
