# Generated by Django 5.2.1 on 2026-09-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_fix_official_bot_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='last_sandbox_error',
            field=models.TextField(blank=True, default='', help_text='Most recent Docker sandbox error for this model (e.g. missing data file). Cleared automatically after a successful move.'),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='last_sandbox_error_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent sandbox error.', null=True),
        ),
    ]
