# Generated by Django 5.2.1 on 2026-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_add_last_sandbox_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamemodel',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='Human-readable problems from the last check_model() run.'),
        ),
        migrations.AddField(
            model_name='usergamemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', help_text='Result of the last model_check.check_model() contract check.', max_length=20),
        ),
    ]
