# Generated by Django 5.2.1 on 2026-10-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_customuser_gladiator_character_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country of residence. Blank = not set yet.', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_locked',
            field=models.BooleanField(default=False, help_text='True once the country has been saved; users cannot change it afterwards.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_set_at',
            field=models.DateTimeField(blank=True, help_text='When the country was saved (and locked).', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_flag',
            field=models.BooleanField(default=True, help_text="Show the country flag next to the username on the user's profile page."),
        ),
        migrations.CreateModel(
            name='CountryChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_country', models.CharField(blank=True, max_length=2)),
                ('new_country', models.CharField(blank=True, max_length=2)),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
