# Generated by Django 5.2.1 on 2026-10-03 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_country_of_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('chess', 'Chess'), ('breakthrough', 'Breakthrough')], max_length=20)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('error', 'Error')], default='queued', max_length=10)),
                ('verdict', models.CharField(blank=True, choices=[('', 'None'), ('pass', 'Pass'), ('fail', 'Fail'), ('platform_error', 'Platform error')], default='', max_length=20)),
                ('lines', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game_type', '-created_at'], name='diagrun_user_game_created')],
            },
        ),
    ]
