# Generated by Django 5.2.1 on 2026-02-25 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_add_comment_model'),
        ('tournaments', '0007_tournament_announcement_tournament_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon displayed next to the category name.', max_length=10)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown supported: **bold**, *italic*, `code`, [links](url).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Bumped whenever a new reply is posted.')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked threads cannot receive new replies.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.category')),
                ('linked_game', models.ForeignKey(blank=True, help_text='Optionally link a replay to this thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.game')),
                ('linked_tournament', models.ForeignKey(blank=True, help_text='Optionally link a tournament to this thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Markdown supported.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for a top-level reply; set to nest under another post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
