# Generated by Django 5.2.1 on 2026-02-25 19:40

from django.db import migrations


CATEGORIES = [
    {"name": "General Discussion",    "slug": "general-discussion",    "icon": "💬", "description": "Broad discussions about AI, machine learning, and the platform.",           "ordering": 1},
    {"name": "Game & Strategy",       "slug": "game-strategy",         "icon": "♟️",  "description": "Opening theory, endgame tablebases, evaluation tuning, and more.",          "ordering": 2},
    {"name": "Tournaments & Events",  "slug": "tournaments-events",    "icon": "⚔️",  "description": "Talk about upcoming, ongoing, and past tournaments and gauntlets.",         "ordering": 3},
    {"name": "Help & Feedback",       "slug": "help-feedback",         "icon": "❓", "description": "Need help uploading, debugging, or improving your AI? Ask here.",            "ordering": 4},
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("forum", "Category")
    for cat in CATEGORIES:
        Category.objects.get_or_create(slug=cat["slug"], defaults=cat)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("forum", "Category")
    slugs = [c["slug"] for c in CATEGORIES]
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
